### ISSUE TITLE
Question about extension zips and doc examples required

### ISSUE THREAD

**Issue by 163a** [dynatrace-oss/dynatrace-monitoring-as-code#113]
Question: **Can monaco handle configuration of extensions, such as JMX extensions using zip binary as per API?**

Suggestion: _We need an example on how to write the `extension` monitoring-as-code configuration._

**Comment by UnseenWizzard** [comment]
Hi @163a monaco handles the zip-ing of JMX extensions, so that you can check in just the json that defines it
There's an example of an extension here https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/tree/main/cmd/monaco/test-resources/integration-all-configs/project/extension

There is however really no documentation of this (as far as I could see)... We'll need to improve that!

**Comment by 163a** [comment]
Thankyou @UnseenWizzard
