### ISSUE TITLE
Download is not removing non-standard indentifiers - calculated-metrics-service

### ISSUE THREAD

**Issue by anton-freyberg** [dynatrace-oss/dynatrace-monitoring-as-code#178]
**Describe the bug**
when trying to deploy calculated service metrics I downloaded from an environment, I have to change all entityIDs to "null", since these cannot be prefixed when deploying. 

This is the error I got:     Response was: {"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"entityId","message":"Not allowed to define a service metric with an entityId","parameterLocation":"PAYLOAD_BODY","location":null}]}}, responsible config: project\calculated-metrics-service\MoneynewResponsetimeinservicebooking.json

**How to reproduce**
 I just downloaded the whole environment and exported the calculated service metrics in the folder below 
[project.zip](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/files/5982291/project.zip)
Then I deleted a metric in the environment and tried to deploy the newly created project

**Expected behavior**
By deploying the project above, I was expecting to deploy the metric I deleted in the UI

**Log output**
If applicable, add log snippet to help explain your problem.
[20210215-153855.log](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/files/5982305/20210215-153855.log)

**Environment (please complete the following information):**
 - OS: Win 10
 - Tool version [e.g. 1.3.1]

**Additional context**

**Comment by tatomir146** [comment]
@diegorqc are the ID's stripped from configuration after download? I don't see anything in documentation.

**Comment by anton-freyberg** [comment]
So this does not seem to be an isolated case. Same with the application (or application-web) folders.  Identifiers are kept and produce errors. In the case of  application-web, I tried to deploy some config and this was the error:

 2021-02-15 17:45:33 ERROR Deployment to integration failed with error Failed to upsert DT object Wohnbaubank OBK (HTTP 400)!
    Response was: {"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"id","message":"Payload must not have an id in a POST request.","parameterLocation":"PAYLOAD_BODY","location":null}]}}, responsible config: deploy\application-web\WohnbaubankOBK.json
2021-02-15 17:45:33 ERROR Errors during deployment! Check log!

**Comment by diegorqc** [comment]
@tatomir146 yes the ID's are stripped out, but currently we are only stripping out the ones that start with "id" as keyword. @anton-freyberg  About the calculated service metric, I've tried the scenario you mention, if you delete manually the entityIDs to null, are you getting what you expected in the Dynatrace environment? or are you missing information because you have deleted this field? I'm not sure if for all the download configs for calculated service metrics we should delete this property or the the Dynatrace API should accept this payload with an entity ID already in place. @didiladi  you might know more than me about this

**Comment by anton-freyberg** [comment]
I set the id to "null", so: entityID: null; 
I am pretty sure it worked. I would have to recreate. But at least all the sample in the mac directory had entityID: null and they worked just fine.

**Comment by anton-freyberg** [comment]
So, the identifier is gone for calculated service metrics. Works perfectly

**Comment by anton-freyberg** [comment]
I downloaded some calculated service metrics at at customer, and for some reason some entityIDs were null and some not. Also IDs are downloaded for custom services as well.

**Comment by UnseenWizzard** [comment]
As in #669 & #668 download is not stripping the non-default identifier here. 

As mentioned in the comments above this doesn't always happen, as entityID may be null - in which case re-upload will work.

**Expected behavior**
Download strips the toplevel `entityId` key the same way as `id` and is able to both update and newly create a downloaded calculated-metrics-service configuration.
