### ISSUE TITLE
Application with multiple detection rules fails with "Given application detection rule duplicates rule"

### ISSUE THREAD

**Issue by miha-anzur** [dynatrace-oss/dynatrace-monitoring-as-code#254]
Hello 
During the upload of downloaded data with monaco following error is reported

2021-03-12 11:13:35 ERROR Deployment to perform failed with error Failed to upsert DT object Web admin tools (HTTP 400)!
    Response was: {"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"","message":"Given application detection rule duplicates rule 57edee13-13ce-4202-bfbe-8b68cd9674f7","parameterLocation":"PAYLOAD_BODY","location":null}]}}, responsible config: perform/app-detection-rule/Webadmintools.json

Create application with multiple detection rules.
Execute:
monaco download -e environment.yaml
-- data stored to folder perform

Execute:
monaco -e environment.yaml -v perform/

**Comment by tatomir146** [comment]
@diegorqc maybe you can help here?

**Comment by diegorqc** [comment]
I will need more details about the yaml file and json file downloaded, but at first this looks similar to #179 specifically the comment from Kristof. Also I noticed that the  [Dynatrace API for app detection rules](https://www.dynatrace.com/support/help/dynatrace-api/configuration-api/rum/application-detection-configuration/get-all/) has 3 possible values when getting the configs. Only 2 of those values include a name, so this might be something to consider, since we are using the name to identify the config

**Comment by mdicss** [comment]
See also: https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/discussions/293#discussioncomment-619795
