### ISSUE TITLE
Fix documentation: -- or -

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#42]
Readme suggests the flags use double dashes. For example `--dry-run` but the v1.0.0 binary still uses single dashes eg. `-dry-run`

**Comment by Dynatrace-Adam-Gardner** [comment]
More confusingly, the help menu in the tool itself suggests:

```
$ ./monaco
Please provide environments yaml with -e/--environments
```

But the output shows:

```
Usage of arguments:
  -environments string
        Mandatory yaml file containing environments to deploy to.
```

Finally, the tool **actually** excepts both `-environments` and `--environments`

**Comment by tatomir146** [comment]
Go flags support both cases, and I wouldn't change that behaviour. As it's common in UNIX we should support both UNIX `-e` and GNU style flags `--environments`. But I agree with you, we need more consistency and we should make sure:
- shorthand options are in UNIX style: `-e`, `-p`
- long options are in GNU style: `--environments`, `--project`

**Comment by UnseenWizzard** [comment]
The issue here is that Go supports `-` for shorthand and long options, as well as the standard `-`-shortand & `--`-long options. 

The documentation was purposely written to follow the norm for options. 

The help text is generated by Go flags - which shows the single dash exclusively - I'm not aware of a way to change that. 

Funnily enough, even the documentation of flags reads: 
> Use -h or **--help** flags to get automatically generated help text for the command-line program.

**Comment by Dynatrace-Adam-Gardner** [comment]
Gotcha. I've learned something new today :) I'll close this as not an issue.
