### ISSUE TITLE
Improve cli design

### ISSUE THREAD

**Issue by patrickpichler** [dynatrace-oss/dynatrace-monitoring-as-code#45]
As of right now, the cli is not really obvious to use. There are multiple
flags which are required, some which trigger different actions also we
have positional elements. 

This ticket was created to kick off a discussion and collect proposals 
on how to improve the cli design.

**Comment by neox5** [comment]
I think to apply configurations should be the `default` action.
And deleting should be a separate command/flag.
Maybe switch to [cobra](https://github.com/spf13/cobra) in the long run.

Was there any previous consideration why both actions would run?

**Comment by UnseenWizzard** [comment]
the logic of upload & delete in one step was mainly to insure the state as set in the config repo with one run of the tool as far as I remember. 

But I agree, that while we're thinking about updating how the tool works, it makes sense to split these things into commands - maybe with one that runs both add and delete. 
+1 for cobra

What I'd like to see: 
* commands for actions
* with arguments for everything that's required
* and flags for optional input

e.g. 

`monaco deploy environments.yaml -se prod`

`monaco delete delete.yaml environments.yaml`

`monaco download environments.yaml -se prod`

**Comment by patrickpichler** [comment]
I did some research into possible cli frameworks and I have to say
that I personally do not like `cobra` that much. It seems way too 
complicated.

Here some alternatives:
* https://github.com/alecthomas/kong
* https://github.com/urfave/cli/

From what I've seen I prefer [kong](https://github.com/urfave/cli/)

**Comment by didiladi** [comment]
I guess someone has to play the bad cop here :policeman: : I'm not very keen on breaking the backward compatibility at this point in time. We just released version 1.0 to GitHub and I don't think that this would send the right message to the users of `monaco`.

Although I have to admit: breaking the compatibility of the CLI is probably not as disruptive as breaking the compatibility for the config structure (yamls, environments, references, ...). But still: I'm not a huge fan of it.

However, what we can think of:
* Introducing the new commands *in addition* to the old flag-based approach.
* As a first step (early-adopter):
** Label the new commands as `Beta`.
** Print a warning when someone uses the new commands that they could change in the future (because they are still in `Beta`).
* As a second step (when we know the commands are stable and battle-proven):
** Promote the new command-based approach to be the new way to go and remove the warning message when someone uses it.
** Print a warning if someone uses the cold flag-based approach.
* As a third step:
** Remove the old flag-based approch from the tooling.

What do you think?

**Comment by patrickpichler** [comment]
I guess it would be best to add some kind of env varible like `NEW_CLI` which 
will activate this new interface would be nice. So a users can decide them self 
if they want to go with the new version of the cli or not. 

But I fully agree, that we should not break backwards compatibility yet :+1: 

I wanted to prototype some things to actually get a feeling for how it could look
like in the feature.

**Comment by didiladi** [comment]
@patrickpichler I know, your PR was my "wakeup-call" for me to finally write down my thoughts about this topic. :) I like your idea of the env var. Otherwise we might run into unforseen issues where users try to mix commands and flags from both versions - that would be uncool.

As a personal wish-list to a CLI re-design:
* Help commands all the way (multiline, with examples and extensive documenataion on what every command and flag does)
* Support for shell-completion
* Extensibility
* Possibility to slowly deprecate commands/flags.

**Comment by patrickpichler** [comment]
I will add the current cli interface and make it switchable via the env var :+1: 

Yes shell-completion would be important. From what I've seen the cli framework
I used for this prototype supports completions, but I didn't have a closer look yet.

**Comment by patrickpichler** [comment]
@didiladi I added the possibility to switch between configs. 

Would be nice if you could give it a try ;)

**Comment by patrickpichler** [comment]
What exactly do you mean with `Possibility to slowly deprecate commands/flags.`? 
Wouldn't this basically work by updating the documentation that a certain flag
is now deprecated and will be removed in the next major release?

**Comment by didiladi** [comment]
Yes, would be cool to have:
* An updated documentation - I guess this one is easy
* And a warning if the user still uses them

**Comment by Megatron1024** [comment]
Hi Team,

I did a backup of the environment and got good results:

![image](https://user-images.githubusercontent.com/19298968/203872314-f6c231bf-6450-4186-8fe0-88b92eaa5b21.png)


My feedback:

1. Log processing rules are not appearing to be backed up.
2. Permissions required by the access token are not mentioned. It would be great to have that listed at least in the comments of the file or as an FYI while running the script.
3. Create a Powershell version of the script in addition for the shell script.

**Comment by UnseenWizzard** [comment]
Hi @Megatron1024 , 

thanks for your feedback. 

1. Log processing rules are configured via the Settings 2.0 API, which is not supported by monaco. We are currently working on supporting this. 
2. You can find the required token permissions for each configuration type in the documentation: https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/configuration/configTypes_tokenPermissions
For downloading your configuration you will already need a token with at least the relevant `read` permissions - so to be honest I'm not too sure if printing the respective `write` permission on download? 

You removed 3. it seems but as you've mentioned a script originally, did you find monaco via @Dynatrace-Adam-Gardner's [recent post about a backup script](https://www.linkedin.com/posts/agardner1_dynatrace-quicktip-gitops-activity-7001453303083536384-3XE5?utm_source=share&utm_medium=member_desktop)? :)

**Comment by Megatron1024** [comment]
Thanks, @UnseenWizzard, for your response.

Great to know that you are currently working to support this. Log processing rules are a lot of work, so getting it through code would be helpful.

Yeah, I used Monaco via @Dynatrace-Adam-Gardner 's post ;) The permissions and others can be `echoed `during the script start-up. Something Adam can potentially add if he likes to add them :)
