### ISSUE TITLE
Duplicate Alerting Profiles

### ISSUE THREAD

**Issue by FinUD** [dynatrace-oss/dynatrace-monitoring-as-code#587]
When running the same project multiple times against an environment with the same variables it creates multiple alerting profiles of the same name and configuration. The project contains an alerting profile, app detection rule, web application, auto tag and a management zone. The only thing that duplicates is the alerting profile.

I expected, just like with every other configuration, for only one alerting profile to be created and if the project was run again with the exact same variables no duplicates to also be created.

In the attached .zip is my project. Within that project is a bash script which collects the environment variables and then runs Monaco. This is how I have been running my project.
[Projects.zip](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/files/8375480/Projects.zip)

Monaco command:
monaco -e=env/environments.yml -p=projects/newApp

Environment:
- OS: Ubuntu 20.04.3 LTS
- Monaco version: 1.7.0

**Comment by UnseenWizzard** [comment]
Hi @FinUD , sorry for the late reaction on this! 

The problem here lies in how you're naming the alerting profile. 
monaco uses the `name` property you define in the yaml to check if a configuration already exists. 

For your alerting profile you're setting the `name` to the `MONACO_APP_NAME` environment variable, but then in the json you're naming the actual configuration as `{{ .name }} Alerts`. 

So on upload monaco will look for existing configs named `MONACO_APP_NAME` but not find any, as the config is actually `MONACO_APP_NAME Alerts`. 

To fix this issue in your configuration append the Alerts to the `name` property in the yaml, not adding it in the json. 

alerting-profile/alerting-profile.yaml
```
config:
  - alerting-profile: "alerting-profile.json"

alerting-profile:
  - name: "{{ .Env.MONACO_APP_NAME }} Alerts"
  - mzid: "projects/newApp/management-zone/management-zone.id"
```

and in the json
```
{
  "displayName": "{{ .name }}",
  "mzId": "{{ .mzid }}",
  "rules": [ ....
```
