### ISSUE TITLE
app-detection-rule-v2 is identical to app-detection-rule

### ISSUE THREAD

**Issue by agardnerIT** [dynatrace-oss/dynatrace-monitoring-as-code#728]
**Describe the bug**
`app-detection-rule` is deprecated by a config type that is actually identical.

```
	"app-detection-rule": {
		apiPath:        "/api/config/v1/applicationDetectionRules",
		isDeprecatedBy: "app-detection-rule-v2",
	},
	"app-detection-rule-v2": {
		apiPath:            "/api/config/v1/applicationDetectionRules",
		isNonUniqueNameApi: true,
	},
```

**Comment by Laubi** [comment]
Hi @agardnerIT, thank you for reaching out and creating the ticket.

You're right, the config type is identical, but the -v2 API is marked as `isNonUniqueNameApi: true `. 
We decided to introduce a new version so that existing configurations don't break.

[We have a guide on how to migrate the APIs concerning the uniqueness of the names.](https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/Guides/deprecated_migration/)
