### ISSUE TITLE
Define some install steps/requirements

### ISSUE THREAD

**Issue by dieselsteve** [dynatrace-oss/dynatrace-monitoring-as-code#82]
Hi all,

as the subject already mentions please create some small steps to install/setup monaco or at least some prerequisitest to install... Not everybody has go already installed.

Thanks,
Steve

**Comment by CruzanCaramele** [comment]
I will include this as part of enhancing the documentation and provide the instructions for various platforms

**Comment by UnseenWizzard** [comment]
@dieselsteve just to be sure, you are looking for install steps because you wish to contribute to the tool, or you're looking for a way to install, so you can run it? 

For just running it, you find releases here and shouldn't need go installed at all: https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/releases

**Comment by dieselsteve** [comment]
@UnseenWizzardI an unskilled  Unix  user doesn't know what to do with the packages you already prepared so just a few bullet points would be great!

rgds Steve

**Comment by UnseenWizzard** [comment]
@dieselsteve I see, just wanted to be sure we'd add the right info to the right part of the documentation 👍
